CREATE TABLE IF NOT EXISTS a17132_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(40) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS a17132_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    player_name VARCHAR(40) NOT NULL,
    score INT NOT NULL,
    time_elapsed INT NOT NULL,
    lives_lost INT NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX (score),
    INDEX (criado_em),
    CONSTRAINT fk_a17132_stats_user FOREIGN KEY (user_id) REFERENCES a17132_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
